export const FETCH_ARTICLES = 'fetchArticles'
export const FETCH_ARTICLE = 'fetchArticle'
export const FETCH_COMMENTS = 'fetchComments'
export const FETCH_TAGS = 'fetchTags'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const CHECK_AUTH = 'checkAuth'
