export const SET_ARTICLES = 'setArticles'
export const SET_ARTICLE = 'setArticle'
export const SET_COMMENTS = 'setComments'
export const SET_TAGS = 'setTags'
export const SET_AUTH = 'setUser'
export const SET_ERROR = 'setError'
export const PURGE_AUTH = 'logOut'
